global:
    scrape_interval: 5s
    evaluation_interval: 5s

    external_labels:
        monitor: 'codelab-monitor'

rule_files:

scrape_configs:
    - job_name: 'prometheus'
      static_configs:
          -   targets: ['traefik:8082']

    -   job_name: 'spring-actuator'
        metrics_path: '/actuator/prometheus'
        scrape_interval: 5s
        static_configs:
            -   targets: ['traefik:80']
