global:
    scrape_interval: 5s
    evaluation_interval: 5s

    external_labels:
        monitor: 'codelab-monitor'

rule_files:

scrape_configs:
    - job_name: 'node'
      static_configs:
          -   targets: ['traefik:8082']
